<html>
<body>
    <a class="btn" href="register.php">Voltar</a>
    <h1> <strong>Termos e Condições</strong></h1>

<p>Aorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sollicitudin purus sit amet mattis aliquet. Etiam vitae tellus scelerisque, consectetur lacus vitae, facilisis tortor. Aliquam erat volutpat. Proin auctor nulla quis arcu sagittis, non luctus lacus porttitor. Duis convallis aliquam scelerisque. Duis efficitur sapien quis quam interdum laoreet. Aenean in risus enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rutrum massa, in ullamcorper enim. Morbi luctus lorem erat, et finibus est molestie placerat. Integer semper vulputate nibh, id auctor quam. Etiam non sodales quam. Duis sit amet erat a leo consectetur gravida. Integer porta diam vel nulla laoreet, et euismod neque faucibus.

<p>Aauris vitae viverra nunc. Suspendisse potenti. Maecenas eget felis eget dui tincidunt viverra. Aenean ligula velit, sagittis et laoreet ac, iaculis in nisi. Fusce vel ipsum sit amet felis accumsan eleifend. Vestibulum mollis quam et enim congue, hendrerit bibendum nisl convallis. Quisque sit amet laoreet diam, vel mattis sapien. Quisque ut lacus eu eros interdum sodales. Donec tortor massa, aliquet sit amet suscipit ac, convallis ac elit. Donec nisi sapien, fringilla sed rutrum quis, tincidunt vitae dolor. Donec eget accumsan magna. Vivamus elementum et dui ut tempor.

<p>Aras pharetra tincidunt nisl vitae consequat. Nullam id varius justo. Quisque pellentesque nisl vitae turpis molestie, nec maximus est posuere. Curabitur sit amet augue erat. Curabitur nec commodo tellus. Aliquam erat volutpat. Vestibulum ac mi porttitor, facilisis tellus et, tempus risus. Suspendisse vel leo interdum, mattis ex vel, ultricies arcu. Fusce eget sapien at nibh tincidunt vestibulum sed at turpis. Integer eget eros tempor, sodales massa ut, vehicula eros. Donec malesuada nisl erat, nec finibus velit ultrices vel.

<p>Aullam dictum mi lectus, in ullamcorper magna sodales ut. Nulla facilisi. In feugiat pharetra fringilla. Cras ultricies cursus enim. Mauris ut elit ut orci porta vestibulum sit amet vitae urna. Praesent lacinia tristique posuere. Nam dui magna, tristique at lacus sit amet, volutpat tincidunt diam. Vivamus convallis sollicitudin erat, non blandit eros rhoncus eget. Nam scelerisque neque neque, eget accumsan libero eleifend ac.

<p>Aulla velit lorem, tincidunt eleifend lorem a, vestibulum porta ante. Donec mollis egestas massa quis pellentesque. Aliquam luctus neque eget ante venenatis, quis pulvinar nibh bibendum. Integer a mattis leo. Nam feugiat pharetra neque, ac volutpat nunc porttitor elementum. Sed rutrum eget mauris eu pulvinar. Nam vitae elit egestas, posuere lacus in, maximus urna.

<p>Araesent eget arcu sem. Phasellus in lorem urna. Nulla ut erat lectus. Mauris justo justo, consequat at consequat ut, aliquet sit amet orci. Integer ut varius lacus. Donec sit amet bibendum dui, sed dignissim augue. Vivamus faucibus a mi a finibus. Nullam neque odio, rutrum eget egestas id, commodo eget odio. Integer fringilla erat at nunc ultricies venenatis. Integer neque nulla, suscipit sit amet dictum id, ornare at leo. Sed eu congue nunc.

<p>Ausce gravida orci sit amet massa suscipit, porttitor dictum risus pretium. Vestibulum eleifend enim ut lorem bibendum rhoncus. Cras ut convallis ligula, ut mollis est. Aliquam sit amet diam hendrerit turpis finibus lacinia. Donec hendrerit magna sit amet mauris pellentesque, et volutpat ipsum venenatis. Etiam a varius leo. Nunc consequat, nisi vel malesuada imperdiet, orci diam consequat leo, at vehicula nisl massa a velit. Maecenas euismod nulla felis, id commodo lectus ultricies id. Donec tincidunt rutrum semper.

<p>Aellentesque tempor lorem leo, a blandit ex mollis eu. Quisque eu est ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. In scelerisque felis et urna malesuada pretium. Vestibulum et erat neque. Sed condimentum orci ac eros luctus, in gravida purus finibus. Vestibulum aliquet placerat consequat. Nulla at erat ex. Praesent vulputate felis vel tellus maximus suscipit. Aliquam venenatis ornare nunc a pretium.

<p>Anteger venenatis ligula eu tempor mollis. Cras rutrum scelerisque tellus, sit amet aliquam erat semper et. Duis ac purus in odio porttitor eleifend. Morbi maximus ornare dictum. Nulla nec nunc in sem elementum fringilla. Integer malesuada orci vel mattis finibus. Donec elementum ipsum nulla, a ullamcorper magna volutpat a. Suspendisse aliquet blandit odio at porttitor. Sed tincidunt at lectus laoreet fermentum. Aenean maximus enim a varius porta. Morbi cursus volutpat commodo. Pellentesque purus augue, pretium non massa eget, sagittis ullamcorper dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi scelerisque ac diam nec pellentesque. Suspendisse auctor consequat lorem, nec congue lorem ullamcorper non.

<p>Aorbi pharetra, justo eu vulputate posuere, lorem purus sollicitudin ligula, at volutpat mi ligula ac dui. Quisque ultricies quam vel odio dignissim tincidunt. Cras blandit sollicitudin risus quis scelerisque. Etiam faucibus mi eu nisl finibus, eu suscipit lacus faucibus. Sed aliquam, velit et bibendum pretium, ipsum velit tincidunt nisl, nec lacinia ipsum felis quis erat. Curabitur eget maximus lectus. Aenean faucibus, ipsum eget vulputate euismod, arcu justo dignissim ex, a iaculis ipsum lacus ut nisi. Etiam posuere sodales convallis. Proin vitae erat sed urna varius euismod ac sed massa. Curabitur a elementum velit. Donec ornare tellus quis imperdiet dignissim. Sed blandit euismod eros non euismod.
</body>
</html>